### ISSUE TITLE
Configure labels in aggregation

### ISSUE THREAD

**Issue by albertteoh** [nearmap/libddog#49]
## Context

Explain the conditions which led you to write this issue.

## Problem or idea

The following graph definition is handy because it elegantly defines multiple percentiles in the one query:
```
Request(
                title="ms latency",
                queries=[
                    Query(f"my.query.{percentile}")
                    .agg("avg")
                    .rollup("avg")
                    for percentile in ["95percentile", "median"]
                ],
...
```

However, it results in two timeseries with the same label and with no legend to differentiate the two lines. Fortunately, in this case, we know the top line should be P95 and the other the median just by the definition of these percentiles:

![Screen Shot 2021-10-21 at 4 18 40 pm](https://user-images.githubusercontent.com/26584478/138215958-ec3b76a8-65b2-4345-809c-90d08c527321.png)

![Screen Shot 2021-10-21 at 4 18 48 pm](https://user-images.githubusercontent.com/26584478/138215963-44f406ac-0d9a-47ab-83a3-a9e6a68dea89.png)

The only other way to differentiate them is to edit the graph to see which line refers to which metrics query.

## Solution

This is more a question to start with as there may be a solution to this that I'm not aware of; is there a way to label each queried metric?

**Comment by martinm-nm** [comment]
As discussed over Zoom the way to achieve this would be to explicitly define a Formula for each query and set the alias for it:

```
    query_median = (
        Query("my.query.median")
        .agg("avg")
        .rollup("avg")
    )
    query_p95 = (
        Query("my.query.95percentile")
        .agg("avg")
        .rollup("avg")
    )
    median = query_median.identifier()
    p95 = query_p95.identifier()

    formula_median = Formula(median, alias="median")
    formula_p95 = Formula(p95, alias="p95")

    Request(
        title="ms latency",
        queries=[query_median, query_p95],
        formulas=[formula_median, formula_p95],
        display_type=DisplayType.LINES,
        style=Style(
            palette=Palette.GRAY,
            line_width=LineWidth.NORMAL,
        ),
    )
```

However, the confusing behavior you point out is that in the absence of explicit Formula definitions the `title` of the `Request` is applied to every Formula that is synthesized. This seems wrong and `Request` probably shouldn't have a `title` attribute at all.

**Comment by albertteoh** [comment]
Thanks @martinm-nm, will give this a try.
